import fs from "fs";
import path from "path";

// Function to safely read a file to base64 for PDF embedding
const readFileToBase64 = (fileName: string): string => {
  try {
    const filePath = path.join(process.cwd(), "public", fileName);
    if (!fs.existsSync(filePath)) return "";
    const buffer = fs.readFileSync(filePath);
    return `data:image/png;base64,${buffer.toString("base64")}`;
  } catch (error) {
    console.error(`Error reading ${fileName}`, error);
    return "";
  }
};

export const REPORT_CONSTANTS = {
  CLINIC_NAME: "AntarEye Medical Imaging Lab",
  DISCLAIMER_TEXT:
    "⚠ This report is generated by an AI-assisted screening tool and is NOT a clinical diagnosis. It is intended solely as a decision-support aid for qualified medical professionals. AI predictions may contain errors. Final clinical decisions must be made by a licensed ophthalmologist. © 2026 AntarEye. For professional use only.",
  THEME: {
    primary: "#612840", // oklch(0.38 0.155 25)
    foreground: "#303030",
    mutedForeground: "#737373",
    border: "#e5e5e5",
    destructive: "#a83232",
    warning: "#eab308",
    success: "#22c55e",
  },
  IMAGES: {
    // We load these lazily to avoid running fs.readFileSync on the edge if this file is imported there.
    // The report generation happens in a Node.js route handler, so this is safe.
    getLogo: () => readFileToBase64("logo.png"),
    getPersonPlaceholder: () => readFileToBase64("placeholder-person.png"),
    getNotAvailablePlaceholder: () => readFileToBase64("not-available-image.png"),
  },
} as const;
